// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVRznMr-lnJznhPchcFQkA8suCK4KlZIs',
    appId: '1:103880480812:web:c02eda7886d7c863f75989',
    messagingSenderId: '103880480812',
    projectId: 'eagles-923ab',
    authDomain: 'eagles-923ab.firebaseapp.com',
    storageBucket: 'eagles-923ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8NvW9BPBnkPusX7DmUHGZ4ka14hwTUqk',
    appId: '1:103880480812:android:ed41e9876413f090f75989',
    messagingSenderId: '103880480812',
    projectId: 'eagles-923ab',
    storageBucket: 'eagles-923ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5s3JakMy5SGSIqwEv9uLrQgsvuAn3RLM',
    appId: '1:103880480812:ios:96fb7d70b3b66f32f75989',
    messagingSenderId: '103880480812',
    projectId: 'eagles-923ab',
    storageBucket: 'eagles-923ab.firebasestorage.app',
    iosBundleId: 'com.example.eagles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5s3JakMy5SGSIqwEv9uLrQgsvuAn3RLM',
    appId: '1:103880480812:ios:96fb7d70b3b66f32f75989',
    messagingSenderId: '103880480812',
    projectId: 'eagles-923ab',
    storageBucket: 'eagles-923ab.firebasestorage.app',
    iosBundleId: 'com.example.eagles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVRznMr-lnJznhPchcFQkA8suCK4KlZIs',
    appId: '1:103880480812:web:294ef43bad82a450f75989',
    messagingSenderId: '103880480812',
    projectId: 'eagles-923ab',
    authDomain: 'eagles-923ab.firebaseapp.com',
    storageBucket: 'eagles-923ab.firebasestorage.app',
  );

}